baseURL = 'https://mperetto.github.io/blog/'
languageCode = 'en-us'
title = 'Marco Peretto - Blog'
theme = 'ronu-hugo-theme'

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
	
[[menu.main]]
	name = "Blog"
	url = "/posts/"
	weight = 2
